version: "3"

services:
  # expose port: 25500
  # http://192.168.93.2:25500/sub?target=clash&url=https%3A//www.jinkela.site/link/xfTBMK0hw35XcYyy%3Fsub%3D3&list=true&include=%28%3F%3D.%2A%E9%A6%99%E6%B8%AF%29%28%3F%3D.%2A1.5x%29
  subconverter: # https://github.com/tindy2013/subconverter
    image: tindy2013/subconverter:latest
    network_mode: host
    # ports: 
    #   - "25500:25500"
    restart: always
    container_name: subconverter
    dns:
      - 8.8.8.8
      - 114.114.114.114
      - 127.0.0.1
  clash-premium-ui:
    build: .
    container_name: clash
    network_mode: host
    # 禁用swap
    # mem_limit: 200m
    # memswap_limit: 200m
    restart: always
    # 使用clash-premium的docker镜像无法创建tun: https://github.com/Dreamacro/clash/issues/736
    cap_add: 
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 114.114.114.114
    volumes: 
      # - type: bind
      #   source: "${PWD}/yacd-gh-pages"
      #   target: /ui
      #   read_only: true
      - type: bind
        source: "${PWD}/config.yaml"
        target: /root/.config/clash/config.yaml
        read_only: true
    depends_on: 
      - subconverter
