version: "3"

services:
  clash:
    image: navyd/clash:latest
    container_name: clash
    network_mode: host
    restart: always
    # [How do I break a string in YAML over multiple lines?](https://stackoverflow.com/a/21699210/8566831)
    command: >
      -f /config.yaml
      -b clash
      -d /clash_dir
      -u nobody
      -t 20

    # 仅使用cap_add将无法代理本机docker
    # cap_add:
    # 使用clash-premium的docker镜像无法创建tun: https://github.com/Dreamacro/clash/issues/736
    #   - NET_ADMIN
    # 使用sysctl支持代理本机docker 内部流量
    privileged: true
    devices:
      - /dev/net/tun
    volumes:
      - ./config.yaml:/config.yaml
      - ./clash_dir:/clash_dir
    # 自定义dns 当clash作为本地上游dns时 clash启动时无法找到可用的dns
    dns:
      - 8.8.8.8
      - 119.29.29.29
      - 127.0.0.1
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 400M
        reservations:
          memory: 50M
