version: "3"

services:
  clash-premium-ui:
    image: clash-premium-ui
    container_name: clash
    network_mode: host
    restart: always
    # 使用clash-premium的docker镜像无法创建tun: https://github.com/Dreamacro/clash/issues/736
    cap_add: 
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 114.114.114.114
    volumes: 
      - type: bind
        source: "${PWD}/config.yaml"
        target: /root/.config/clash/config.yaml
        read_only: true
